name: duszamobile2021
description: An app to calculate your expanses!

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^4.2.0
  jiffy: ^4.1.0
  monet: ^0.1.0
  shared_preferences: ^2.0.8
  uuid: ^3.0.5

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^9.2.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
