name: duszamobile2021
description: An app to calculate your expenses!

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  expandable: ^5.0.1
  fl_chart: ^0.40.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^4.2.0
  fluttertoast: ^8.0.8
  jiffy: ^4.1.0
  monet: ^0.1.0
  pdf: ^3.6.1
  printing: ^5.6.0
  rflutter_alert: ^2.0.4
  shared_preferences: ^2.0.8
  toggle_switch: ^1.3.0
  uuid: ^3.0.5

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^9.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 100
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
